import Head from "next/head";
import { FC, ReactNode } from "react";
import Footer from "../components/Footer";
import Navbar from "../components/Header/Navbar";
import { Toaster } from "react-hot-toast";
import { AnimatePresence } from "framer-motion";
import MiniCart from "../components/Shop/miniChat";
import { useRecoilValue } from "recoil";
import cartState from "../recoil/cartState";

const Layout: FC<{ children: ReactNode }> = ({ children }) => {
	const miniCart = useRecoilValue(cartState);

	return (
		<>
			<Head>
				<title>MatteBlack</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="overflow-x-hidden">
				<AnimatePresence>{miniCart && <MiniCart />}</AnimatePresence>
				<Toaster />
				<Navbar />
				{children}
				<Footer />
			</main>
		</>
	);
};

export default Layout;
